import type { Metadata } from "next";
import '@/styles/main.scss';
import Searchbar from "./components/Searchbar";
import Sidebar from './components/Sidebar';

export const metadata: Metadata = {
  title: "Soole Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex">
      <Sidebar/>
     <div className="d-flex gap-4 d-flex-1 flex-column">

      <Searchbar/>
        <main className="d-flex-1">
          {children}
          </main>
     </div>
      </body>
    </html>
  );
}
